### ISSUE TITLE
Junction Deviation

### ISSUE THREAD

**Issue by pnoll1** [PrusaOwners/Marlin#25]
I've been getting good print results with the default values after using it for ~2 weeks.  I would recommend turning this on to take advantage of the more advanced motion control it provides.

**Comment by pnoll1** [comment]
also classic jerk accel may have some issues: https://github.com/MarlinFirmware/Marlin/issues/12540

**Comment by pnoll1** [comment]
lack of docs on tuning is the downside. see https://github.com/MarlinFirmware/MarlinDocumentation/issues/500

**Comment by stahlfabrik** [comment]
We activated in our configuration
