### ISSUE TITLE
S Curve Accel requires testing

### ISSUE THREAD

**Issue by pnoll1** [PrusaOwners/Marlin#26]
There have been some reports of issues when s curve accel is enabled.  https://github.com/MarlinFirmware/Marlin/issues/12491 is one of them.  I believe @stahlfabrik also had some issues that may be connected to it.  

I'll try to make some time for testing.

**Comment by stahlfabrik** [comment]
My issues came from somewhere else. Possibly from not initialized eeprom. I am happy so far with s-curve. Closing the issue for now?

**Comment by pnoll1** [comment]
Test print went good.  Motion looked really good,
